<?php $view->extend('layout.phtml') ?>
<?php $view['slots']->set('title', 'Acceso de Usuarios') ?>
<?php $view['slots']->set('description', 'Página de acceso de usuarios a la administración de UECluster.') ?>
<?php $view['slots']->set('header', '') ?>

<section class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>
                <h2>
                    404 Not Found</h2>
                <div class="error-details">
                    Sorry, an error has occured, Requested page not found!
                </div>
                <div class="error-actions">
                    <a href="/" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-home"></span>
                        Take Me Home </a>
                </div>
            </div>
        </div>
    </div>
</section>


<?php $view['slots']->start('scripts') ?>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<?php $view['slots']->stop() ?>
