<?php $view->extend('layout.phtml') ?>
<?php $view['slots']->set('title', 'Error 404!') ?>
<?php $view['slots']->set('description', 'No hemos podido encontrar la página que buscas, disculpa las molestias') ?>
<?php $view['slots']->set('section', 'noticia') ?>

<?php $domain = explode('.', $_SERVER['HTTP_HOST'], 3)[2]  ?>
<?php $view['slots']->start('header') ?>
<header>
    <div class="large">
        <h1><a href="/">EXTRAORDINARIOS</a></h1>
        <nav>
            <ul>
                <li><a href="/de-ruta">De ruta</a></li>
                <li><a href="/paladares">Paladares</a></li>
                <li><a href="/a-punto">A punto</a></li>
                <li><a href="/sorprendete">Sorpréndete</a></li>
            </ul>
        </nav>
        <ul>
            <li<?php echo $domain === 'elmundo.es' ? null : ' class="hide"' ?>><a href="http://www.elmundo.es" target="_blank" onclick="ga('send', 'event', 'External', 'Link', 'El Mundo Header');"><i class="icon-elmundo"></i></a></li>
            <li<?php echo $domain === 'telva.com' ? null : ' hide' ?>><a href="http://www.telva.com" target="_blank" onclick="ga('send', 'event', 'External', 'Link', 'Telva Header');"><i class="icon-telva"></i></a></li>
            <li<?php echo $domain === 'yodona.com' ? null : ' hide' ?>><a href="http://www.yodona.com" target="_blank" onclick="ga('send', 'event', 'External', 'Link', 'Yodona Header');"><i class="icon-yodona"></i></a></li>
            <li><a href="http://www.lidl.es/es/index.htm" target="_blank" onclick="ga('send', 'event', 'External', 'Link', 'Lidl Header');"><i class="icon-lidl"></i></a></li>
        </ul>
    </div>
</header>
<?php $view['slots']->stop() ?>

<main>
    <article>
        <div class="medium">
            <header>
                <h2>Error 404</h2>
            </header>

            <p><strong>Oops... ¡Página no encontrada!</strong></p>
            <p><em>Lo sentimos la página no pudo ser encontrada.</em></p>
            <p><a href="/">Pulse aquí para ir a la página principal</a></p>
        </div>
    </article>
</main>
