<?php $view->extend('layout.phtml') ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <?php if (isset($errors)) : ?>
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>Error!</strong> <?php echo $errors ?>
            </div>
            <?php endif; ?>
            <form method="post" action="/users/save/<?php echo $content['id']; ?>">
                <div class="form-group">
                    <label for="email">Email</label>
                    <div class="input-group">
                        <input class="form-control" name="email" id="email" placeholder="Correo Electrónico" value="<?php echo $content['email']; ?>" type="text">
                        <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-4">
                        <label for="first_name">Nombre</label>
                        <input class="form-control" name="first_name" id="first_name" placeholder="Nombre" value="<?php echo $content['first_name']; ?>" type="text">
                    </div>
                    <div class="col-sm-8">
                        <label for="last_name">Apellidos</label>
                        <input class="form-control" name="last_name"  id="last_name" placeholder="Nombre" value="<?php echo $content['last_name']; ?>" type="text">
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <div class="col-sm-6">
                        <label for="password">Contraseña</label>
                        <input class="form-control" name="password" id="password" placeholder="Contraseña" type="password">
                    </div>
                    <div class="col-sm-6">
                        <label for="confirmPassword">Confirmar Contraseña</label>
                        <input class="form-control" name="confirmPassword"  id="confirmPassword" placeholder="Repetir contraseña" type="password">
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group">
                    <button type="submit" name="Submit" class="btn btn-info btn-lg">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php $view['slots']->start('scripts') ?>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
        function confirmar(mensaje) {
            return confirm(mensaje);
        }
    </script>
<?php $view['slots']->stop() ?>
