<?php $view->extend('layout.phtml') ?>
<?php $author = $data ? $data : $author ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <form method="post" action="/author/save<?php echo $id ? '/'.$id : '' ?>" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-sm-7">
                        <div class="form-group<?php echo isset($errors['name']) ? ' has-error' : '' ?>">
                            <label for="name">Nombre</label>
                            <input class="form-control" name="name" id="name" placeholder="Nombre" type="text" value="<?php echo $view->escape($author['name']) ?>" required>
                            <?php if (isset($errors['name'])) : ?>
                                <span class="help-block"><?php echo $errors['name'][0] ?></span>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group<?php echo isset($errors['position']) ? ' has-error' : '' ?>">
                            <label for="position">Cargo</label>
                            <input class="form-control" name="position" id="position" placeholder="Cargo" type="text" value="<?php echo $view->escape($author['position']) ?>">
                            <?php if (isset($errors['position'])) : ?>
                                <span class="help-block"><?php echo $errors['position'][0] ?></span>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="well">
                            <div class="form-group<?php echo isset($errors['image']) ? ' has-error' : '' ?>">
                                <label for="image">
                                    Imagen <div class="size">150x150</div>
                                </label>
                                <?php if (isset($errors['image'])) : ?>
                                    <span class="help-block"><?php echo $errors['image'] ?></span>
                                <?php endif ?>
                                <input name="image" id="image" type="file" accept="image/jpeg,image/gif,image/png">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group<?php echo isset($errors['twitter']) ? ' has-error' : '' ?>">
                            <label for="twitter">Twitter</label>
                            <input class="form-control" name="twitter" id="twitter" placeholder="Twitter" type="text" value="<?php echo $view->escape($author['twitter']) ?>">
                            <?php if (isset($errors['twitter'])) : ?>
                                <span class="help-block"><?php echo $errors['twitter'][0] ?></span>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group<?php echo isset($errors['link']) ? ' has-error' : '' ?>">
                            <label for="link">Web</label>
                            <input class="form-control" name="link" id="link" placeholder="Web" type="text" value="<?php echo $view->escape($author['link']) ?>">
                            <?php if (isset($errors['link'])) : ?>
                                <span class="help-block"><?php echo $errors['link'][0] ?></span>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" name="Submit" class="btn btn-info btn-lg">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php $view['slots']->start('scripts') ?>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
        function confirmar(mensaje) {
            return confirm(mensaje);
        }
    </script>
<?php $view['slots']->stop() ?>
