<?php $view->extend('layout.phtml') ?>
<?php $content = $data ? $data : $content ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <form action="/save<?php echo $id ? '/' . $id : '' ?>" method="post" enctype="multipart/form-data" id="videoForm">
                <div class="alert alert-warning">
                    <div class="form-group<?php echo isset($errors['webname']) ? ' has-error' : '' ?>">
                        <label for="web">Seleccione la página web a la que pertenece el contenido</label>
                        <select class="form-control select2" id="web" name="webname" required>
                            <option disabled value<?php echo $content ? '' : ' selected' ?>></option>
                            <?php foreach ($GLOBALS['config']['enum']['webs_name'] as $key => $name) : ?>
                                <option value="<?php echo $key ?>"<?php echo $key === $content['webname'] ? ' selected' : '' ?>><?php echo $name ?></option>
                            <?php endforeach ?>
                        </select>
                        <?php if (isset($errors['webname'])) : ?>
                            <span class="help-block"><?php echo $errors['webname'][0] ?></span>
                        <?php endif ?>
                    </div>
                </div>
                <hr>
                <p>
                    <strong>Valoración media</strong>: <span class="label label-warning" style="font-size: 18px;"><?php echo $ratingCount && $ratingSum ? round((int)$ratingSum / (int )$ratingCount, 2) : '' ?></span> (<?php echo (int)$ratingCount ?> valoraciones).
                </p>
                <div class="form-group<?php echo isset($errors['title']) ? ' has-error' : '' ?>">
                    <label for="title">Título</label>
                    <input class="form-control" name="title" id="title" placeholder="Título" type="text" value="<?php echo $view->escape($content['title']) ?>" required>
                    <?php if (isset($errors['title'])) : ?>
                        <span class="help-block"><?php echo $errors['title'][0] ?></span>
                    <?php endif ?>
                </div>
                <div class="form-group<?php echo isset($errors['subtitle']) ? ' has-error' : '' ?>">
                    <label for="subtitle">Subtítulo</label>
                    <input class="form-control" name="subtitle" id="subtitle" placeholder="Subtítulo" type="text" value="<?php echo $view->escape($content['subtitle']) ?>">
                    <?php if (isset($errors['subtitle'])) : ?>
                        <span class="help-block"><?php echo $errors['subtitle'][0] ?></span>
                    <?php endif ?>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group<?php echo isset($errors['date']) ? ' has-error' : '' ?>">
                            <label for="date">Fecha</label>
                            <div class="input-group">
                                <input class="form-control datetimepicker" data-date-format="YYYY-MM-DD HH:mm" name="date" id="date" type="text" value="<?php echo $view->escape($content['date']) ?>">
                                <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
                            </div>
                            <?php if (isset($errors['date'])) : ?>
                                <span class="help-block"><?php echo $errors['date'][0] ?></span>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group<?php echo isset($errors['section']) ? ' has-error' : '' ?>">
                            <label for="sectionTag">Sección</label>
                            <div class="input-group">
                                <input class="form-control" name="section" id="sectionTag" placeholder="Sección" type="text" value="<?php echo $view->escape($content['section']) ?>" autocomplete="off">
                                <div class="input-group-addon"><i class="fa fa-bookmark"></i></div>
                            </div>
                            <?php if (isset($errors['section'])) : ?>
                                <span class="help-block"><?php echo $errors['section'][0] ?></span>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="col-sm-6 hideable">
                        <div class="form-group<?php echo isset($errors['tags']) ? ' has-error' : '' ?>">
                            <label for="tags">Etiquetas</label>
                            <p class="info laprevia"><small>Las etiquetas se deben introducir estrictamente en el siguiente orden: Jornada, Aficionado 1, Aficionado 2, Equipo 1, Equipo 2</small></p>
                            <div class="input-group">
                                <input class="form-control" name="tags" id="tags" placeholder="Etiquetas" type="text" value="<?php echo $view->escape($content['tags']) ?>" autocomplete="off">
                                <div class="input-group-addon"><i class="fa fa-tags"></i></div>
                            </div>
                            <?php if (isset($errors['tags'])) : ?>
                                <span class="help-block"><?php echo $errors['tags'][0] ?></span>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 hideable">
                        <div class="form-group<?php echo isset($errors['vimeo']) ? ' has-error' : '' ?>">
                            <label for="vimeo">ID del vídeo de Vimeo</label>
                            <p class="info loquehayquever"><small>Url de los videos separados por PUNTO y COMA (;). Primero el m3u8</small></p>
                            <div class="input-group">
                                <input class="form-control" id="vimeo" name="vimeo" placeholder="ID de Vimeo" type="text" value="<?php echo $view->escape($content['vimeo']) ?>">
                                <div class="input-group-addon"><i class="fa fa-vimeo-square"></i></div>
                            </div>
                            <?php if (isset($errors['vimeo'])) : ?>
                                <span class="help-block"><?php echo $errors['vimeo'][0] ?></span>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="well">
                            <div class="form-group<?php echo isset($errors['image']) ? ' has-error' : '' ?>">
                                <label for="image">
                                    Imágen
                                    <div class="size">
                                        <span class="noesfutboleslaliga">(1393x877)</span>
                                        <span class="estardondeestes">(990x500)</span>
                                        <span class="espiritufilantropico">(990x500)</span>
                                        <span class="planetainteligente">(1400x768)</span>
                                        <span class="saludesvida">(690x510)</span>
                                        <span class="revivetupelo">(1280x720)</span>
                                        <span class="impulsodigital">(876x1069)</span>
                                        <span class="futurosostenible">(465x341)</span>
                                        <span class="caminosalternativos">(370x498)</span>
                                        <span class="correresdevalientes">(490x275)</span>
                                        <span class="unpaseoporelprado">(352x199)</span>
                                        <span class="estrategiadigital">(1920x1080)</span>
                                        <span class="alimentatusalud">(720x405)</span>
                                        <span class="bodegasybebidas">(670x400)</span>
                                        <span class="innovacionensalud">(768x378)</span>
                                        <span class="pequenosjugadores">(735x413)</span>
                                        <span class="loquehayquever">(630x557)</span>
                                        <span class="nosvemosencasa">(660x461)</span>
                                        <span class="ventanaalfuturo">(593x429)</span>
                                        <span class="potenciatupyme">(1280x720)</span>
                                        <span class="yodonabeautybrandsplace">(700x534)</span>
                                        <span class="theventurespain">(1509x850); sino (824x464)</span>
                                        <span class="vivirmasymejor">(733x489); si es CONTENT o GALLERY (400x367)</span>
                                        <span class="extraordinarios">(980x551) si es una píldora (102x102)</span>
                                        <span class="laprevia">(420x400) si es una noticia (1024x383)</span>
                                    </div>
                                    <?php if ($content['image']) : ?>
                                        <a href="<?php echo $GLOBALS['config']['cdn_url'] ?>/images/<?php echo $view->escape($content['image']) ?>" target="_blank">
                                            <i class="fa fa-eye" aria-hidden="true"></i>
                                        </a>
                                    <?php endif ?>
                                </label>
                                <?php if (isset($errors['image'])) : ?>
                                    <span class="help-block"><?php echo $errors['image'] ?></span>
                                <?php endif ?>
                                <input name="image" id="image" type="file" accept="image/jpeg,image/gif,image/png">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="well">
                            <div class="form-group<?php echo isset($errors['slider']) ? ' has-error' : '' ?>">
                                <label for="slider">
                                    Slider
                                    <div class="size">
                                        <span class="saludesvida">(1920x1280)</span>
                                        <span class="futurosostenible">(1900x980)</span>
                                        <span class="caminosalternativos">(1600x900)</span>
                                        <span class="ventanaalfuturo">(1008x634)</span>
                                        <span class="bodegasybebidas">(1900x1100)</span>
                                        <span class="loquehayquever">(1024x576)</span>
                                        <span class="yodonabeautybrandsplace">(1920x846)</span>
                                    </div>
                                    <?php if ($content['slider']) : ?>
                                        <a href="<?php echo $GLOBALS['config']['cdn_url'] ?>/images/<?php echo $view->escape($content['slider']) ?>" target="_blank">
                                            <i class="fa fa-eye" aria-hidden="true"></i>
                                        </a>
                                    <?php endif ?>
                                </label>
                                <?php if (isset($errors['slider'])) : ?>
                                    <span class="help-block"><?php echo $errors['slider'] ?></span>
                                <?php endif ?>
                                <input name="slider" id="slider" type="file" accept="image/jpeg,image/gif,image/png">
                            </div>
                        </div>
                    </div>
                        <div class="col-sm-4">
                            <div class="well">
                                <div class="form-group<?php echo isset($errors['vertical']) ? ' has-error' : '' ?>">
                                    <label for="vertical">
                                        Vertical
                                        <div class="size">
                                            <span class="estardondeestes">(310x303)</span>
                                            <span class="espiritufilantropico">(310x303)</span>
                                            <span class="saludesvida">(270x300)</span>
                                            <span class="revivetupelo">(547x972)</span>
                                            <span class="unpaseoporelprado">(380x300)</span>
                                            <span class="bodegasybebidas">(350x508) si es evento (495x550)</span>
                                            <span class="yodonabeautybrandsplace">Neceser VIP (1284x707); Objecto de Deseo y Experto (700x700); el resto no subirla</span>
                                        </div>
                                        <?php if ($content['vertical']) : ?>
                                            <a href="<?php echo $GLOBALS['config']['cdn_url'] ?>/images/<?php echo $view->escape($content['vertical']) ?>" target="_blank">
                                                <i class="fa fa-eye" aria-hidden="true"></i>
                                            </a>
                                        <?php endif ?>
                                    </label>
                                    <?php if (isset($errors['vertical'])) : ?>
                                        <span class="help-block"><?php echo $errors['vertical'] ?></span>
                                    <?php endif ?>
                                    <input name="vertical" id="vertical" type="file" accept="image/jpeg,image/gif,image/png">
                                </div>
                            </div>
                        </div>
                    <div class="clearfix"></div>
                </div>
                <div class="form-group<?php echo isset($errors['content']) ? ' has-error' : '' ?>">
                    <label for="content">Contenido</label>
                    <textarea type="text" class="form-control" id="content" name="content"><?php echo $content['content'] ?></textarea>
                    <?php if (isset($errors['content'])) : ?>
                        <span class="help-block"><?php echo $errors['content'][0] ?></span>
                    <?php endif ?>
                </div>
                <div class="alert alert-success">
                    <div class="form-group<?php echo isset($errors['twitter']) ? ' has-error' : '' ?>">
                        <label for="twitter">Texto para Twitter</label>
                        <div class="input-group">
                            <input class="form-control" id="twitter" name="twitter" placeholder="Texto Twitter" type="text" value="<?php echo $view->escape($content['twitter']) ?>" required>
                            <div class="input-group-addon"><i class="fa fa-twitter"></i></div>
                        </div>
                        <?php if (isset($errors['twitter'])) : ?>
                            <span class="help-block"><?php echo $errors['twitter'][0] ?></span>
                        <?php endif ?>
                    </div>
                    <div class="form-group<?php echo isset($errors['facebook']) ? ' has-error' : '' ?>">
                        <label for="facebook">Texto para Facebook</label>
                        <textarea type="text" class="form-control" id="facebook" name="facebook" required placeholder="Texto Facebook"><?php echo $view->escape(stripslashes($content['facebook'])) ?></textarea>
                        <?php if (isset($errors['facebook'])) : ?>
                            <span class="help-block"><?php echo $errors['facebook'][0] ?></span>
                        <?php endif ?>
                    </div>
                    <div class="form-group<?php echo isset($errors['description']) ? ' has-error' : '' ?>">
                        <label for="description">Meta Descripción Google</label>
                        <div class="input-group">
                            <input class="form-control" id="description" name="description" placeholder="Meta Descripción Google" type="text" value="<?php echo $view->escape($content['description']) ?>" required>
                            <div class="input-group-addon"><i class="fa fa-google"></i></div>
                        </div>
                        <?php if (isset($errors['description'])) : ?>
                            <span class="help-block"><?php echo $errors['description'][0] ?></span>
                        <?php endif ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-5">
                        <div class="alert alert-info">
                            <div class="form-group<?php echo isset($errors['author']) ? ' has-error' : '' ?>">
                                <label class="control-label" for="author">Autor</label>
                                <select class="form-control select2" name="author" id="author">
                                    <option value="-1"<?php echo !$content['author_id'] ? ' selected' : '' ?>>Sin Autor</option>
                                    <?php foreach ($authors as $author) : ?>
                                        <option value="<?php echo $author->author_id ?>"<?php echo $author->author_id === $content['author_id'] ? ' selected' : '' ?>><?php echo $author->name ?></option>
                                    <?php endforeach ?>
                                </select>
                                <?php if (isset($errors['author'])) : ?>
                                    <span class="help-block"><?php echo $errors['author'][0] ?></span>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-7">
                        <div class="alert alert-info">
                            <p>
                                <strong>Opciones</strong>
                            </p>
                            <?php if ($content['options']) : ?>
                                <?php foreach (json_decode($content['options'], true) as $key => $option) : ?>
                                    <div class="form-group">
                                        <div class="col-xs-6 col-sm-3">
                                            <input class="form-control" name="option_name[]" type="text" list="options" required value="<?php echo $view->escape($key) ?>">
                                        </div>
                                        <div class="col-xs-6 col-sm-9">
                                            <input class="form-control" name="option[]" value="<?php echo $view->escape($option) ?>" type="text" required>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                <?php endforeach ?>
                            <?php endif ?>
                            <datalist id="options">
                                <?php foreach ($GLOBALS['config']['enum']['options'] as $option) : ?>
                                    <option value="<?php echo $option ?>"><?php echo $option ?></option>
                                <?php endforeach ?>
                            </datalist>
                            <div class="form-group clone">
                                <div class="col-xs-6 col-sm-3">
                                    <select class="form-control" name="option_name[]">
                                        <?php foreach ($GLOBALS['config']['enum']['options_name'] as $key => $name) : ?>
                                            <option value="<?php echo $name ?>"><?php echo $key ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                                <div class="col-xs-6 col-sm-9">
                                    <input class="form-control option-input" name="option[]" placeholder="Opción, doble click o escribe para ver las opciones" type="text">
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <?php if ($id) : ?>
                        <?php if ($content['active'] == 0) : ?>
                            <a href="/edit/active/<?php echo $view->escape($content['id']) ?>" class="btn btn-success btn-lg">Activar</a>
                        <?php else : ?>
                            <a href="/edit/deactive/<?php echo $view->escape($content['id']) ?>" class="btn btn-warning btn-lg">Desactivar</a>
                        <?php endif ?>
                        <a href="<?php echo $view->escape($content['link'], 'path') ?>" class="btn btn-info btn-lg" target="_blank">Previsualizar</a>
                    <?php endif ?>
                    <button type="submit" class="btn btn-primary btn-lg pull-right">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php $view['slots']->start('scripts') ?>
    <!-- Autocomplete -->
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script>
        $('#web').change(function() {
            $('.size span, .hideable .info').hide();
            var section = $(this).val();
            if (section) {
                $('.size .'+section+', .hideable .'+section).show();
            } else {
                $('.size .default').show();
            }
        });
        $(document).ready(function() {
            var section = $('#web').val();
            if (section) {
                $('.size .'+section+', .hideable .'+section).show();
            } else {
                $('.size .default').show();
            }
        });
    </script>
    <script>
    $(function() {
        var tags = <?php echo $autocomplete ?>;
        function split(val) {
            return val.split(/,\s*/);
        }
        function extractLast(term) {
            return split(term).pop();
        }
        $("#sectionTag").autocomplete({
            source: function( request, response ) {
            // delegate back to autocomplete, but extract the last term
                response( $.ui.autocomplete.filter(
                tags, extractLast( request.term ) ) );
            },
            focus: function() {
                // prevent value inserted on focus
                return false;
            },
            select: function(event, ui) {
                var terms = split(this.value);
                // remove the current input
                terms.pop();
                // add the selected item
                terms.push(ui.item.value);
                // add placeholder to get the comma-and-space at the end
                terms.push('');
                this.value = terms.join(', ');
                this.value = this.value.substring(0, this.value.length -2);
                return false;
            }
        });
        $("#tags").autocomplete({
            source: function( request, response ) {
            // delegate back to autocomplete, but extract the last term
                response( $.ui.autocomplete.filter(
                tags, extractLast( request.term ) ) );
            },
            focus: function() {
                // prevent value inserted on focus
                return false;
            },
            select: function(event, ui) {
                var terms = split(this.value);
                // remove the current input
                terms.pop();
                // add the selected item
                terms.push(ui.item.value);
                // add placeholder to get the comma-and-space at the end
                terms.push('');
                this.value = terms.join(', ');
                this.value = this.value.substring(0, this.value.length -2);
                return false;
            }
        });
    });
    $('#videoForm').on('change keyup', '.option-input', function () {
        var empty = false;
        $('.option-input:text').each(function() {
            if ($(this).val() === '') {
                empty = true;
            }
        });
        if (!empty) {
            $(".clone").first().clone().find(".option-input:text").val("").end().appendTo($(".clone").parent());
            empty = false;
        }
    });
    </script>
    <!-- markItUp! -->
    <script src="/js/markitup/jquery.markitup.js"></script>
    <!-- InlineUpload -->
    <script src="/js/markitup/jquery.inlineupload.js"></script>
    <!-- markItUp! toolbar settings -->
    <script src="/js/markitup/sets/html/set.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
    <script src="/js/datetimepicker.es.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.42/js/bootstrap-datetimepicker.min.js"></script>

    <script>
        $(document).ready(function() {
            $(".form-group #content").markItUp(mySettings);
            $(".select2").select2();
            $('.datetimepicker').datetimepicker({
                locale: 'es',
                icons: {
                    time: 'fa fa-clock-o',
                    date: 'fa fa-calendar',
                    up: 'fa fa-chevron-up',
                    down: 'fa fa-chevron-down'
                }
            });
        });
    </script>
<?php $view['slots']->stop() ?>
