<!doctype html>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="es"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" lang="es"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" lang="es"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php $view['slots']->output('title', 'Bienvenido') ?> | UEStudio</title>
        <meta name="description" content="<?php $view['slots']->output('description', 'Innovación, tecnología y digitalización al servicio de la salud de pacientes, médicos y hospitales. Todo lo último en salud.') ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css">
        <link rel="stylesheet" href="/js/markitup/skins/simple/style.css">
        <link rel="stylesheet" href="/js/markitup/sets/html/style.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-css/1.4.6/select2-bootstrap.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css" />
        <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css">
        <link rel="stylesheet" href="/css/main.css">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
    </head>
    <body>
        <?php if ($view['slots']->has('header')) : ?>
            <?php $view['slots']->output('header') ?>
        <?php else : ?>
            <nav class="navbar navbar-default">
                <div class="container-fluid-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">Admin UECluster</a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li<?php echo $section === 'videos' ? ' class="active"' : null ?>>
                                <a href="/"><i class="fa fa-video-camera"></i> Contenido</a>
                            </li>
                            <li<?php echo $section === 'author' ? ' class="active"' : null ?>>
                                <a href="/author/"><i class="fa fa-universal-access" aria-hidden="true"></i> Autores</a>
                            </li>
                            <li<?php echo $section === 'users' ? ' class="active"' : null ?>>
                                <a href="/users/"><i class="fa fa-users"></i> Usuarios</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="http://expomark.es/" target="_blank"><i class="fa fa-power-off"></i> Expomark</a></li>
                            <li><a href="/users/logout"><i class="fa fa-unlock"></i> Salir</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12 text-center">
                        <h1>
                            Administración
                            <small>
                            <?php echo $section === 'users' ? 'Usuarios' : 'Contenido' ?>
                            </small>
                        </h1>
                    </div>
                </div>
                <?php if (isset($_SESSION) && $message = Joelvardy\Flash::message()) : ?>
                    <?php foreach ($message as $key => $value) : ?>
                        <div class="alert alert-<?php echo $key ?> alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <?php echo $value[0] ?>
                        </div>
                    <?php endforeach ?>
                <?php endif ?>
            </div>
        <?php endif ?>

        <?php $view['slots']->output('_content') ?>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/js/jquery.min.js"><\/script>')</script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script>
            $(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
            function confirmar(mensaje) {
                return confirm(mensaje);
            }
        </script>
        <?php $view['slots']->output('scripts') ?>
    </body>
</html>
