<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="UTF-8"/>
    <title>Administración</title>
    <meta name="author" content="expomark.es">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css">
    <link rel="stylesheet" href="/js/markitup/skins/simple/style.css">
    <link rel="stylesheet" href="/js/markitup/sets/html/style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.1/compressed/themes/default.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/pickadate.js/3.5.1/compressed/themes/default.date.css">
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="/css/main.css">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Admin UECluster</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li<?php echo $section === 'videos' ? ' class="active"' : null ?>>
                        <a href="/"><i class="fa fa-video-camera"></i> Contenido</a>
                    </li>
                    <li<?php echo $section === 'users' ? ' class="active"' : null ?>>
                        <a href="/users/"><i class="fa fa-users"></i> Usuarios</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://expomark.es/" target="_blank"><i class="fa fa-power-off"></i> Expomark</a></li>
                    <li><a href="/users/logout"><i class="fa fa-unlock"></i> Salir</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 text-center">
                <h1>
                    Administración
                    <small>
                    <?php
                    if ($section === 'users') :
                        echo 'Usuarios';
                    else :
                        echo 'Contenido';
                    endif;
                    ?>
                    </small>
                </h1>
            </div>
        </div>
        <?php if (isset($_SESSION) && $message = Joelvardy\Flash::message()) : ?>
            <?php foreach ($message as $key => $value) : ?>
                <div class="alert alert-<?php echo $key ?> alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <?php echo $value[0] ?>
                </div>
            <?php endforeach ?>
        <?php endif ?>
    </div>
